### PR TITLE
Update liberator to support Java 11

### PR DESCRIPTION
**Pull request by eggsyntax**
cf https://sea-region.github.com/clojure-liberator/liberator/issues/301

### CODE REVIEW

**Comment by mrichards42** [comment]
I'd say we might as well update the rest of the deps while we're at it (except maybe clojure)

**Comment by eggsyntax** [comment]
> I'd say we might as well update the rest of the deps while we're at it (except maybe clojure)

Couldn't hurt. Maybe worth doing clj too; it's on 1.7 :grimacing:

**Comment by eggsyntax** [comment]
Updated clj to 1.9; all other deps to latest.

**Comment by eggsyntax** [comment]
(All tests passing on this repo and the two repos that depend on it)

**Comment by eggsyntax** [comment]
> Looks good! Will you update the changelog before this gets released?

Good call, will do.

**Pull request merged**
